# Generated by Django 3.0.4 on 2020-03-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametro',
        ),
    ]
